# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: xenial
language: rust
services: docker
sudo: required

# TODO Rust builds on stable by default, this can be
# overridden on a case by case basis down below.

env:
  global:
    # TODO Update this to match the name of your project.
    - CRATE_NAME=railplot

matrix:
  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  include:
    # Linux
    #- env: TARGET=i686-unknown-linux-gnu BINNAME=linux-x86
    - env: TARGET=x86_64-unknown-linux-gnu BINNAME=linux-x64

    # OSX
    #- env: TARGET=i686-apple-darwin BINNAME=osx-x86
    #os: osx
    - env: TARGET=x86_64-apple-darwin BINNAME=osx-x64
      os: osx

    # Windows
    #- env: TARGET=i686-pc-windows-msvc BINNAME=windows-x86
    #os: windows
    - env: TARGET=x86_64-pc-windows-msvc BINNAME=windows-x64
      os: windows

before_install:
  - set -e
  - rustup self update
  - rustup target install $TARGET

install:
  - bash ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  # TODO update `api_key.secure`
  # - Create a `public_repo` GitHub token. Go to: https://github.com/settings/tokens/new
  # - Encrypt it: `travis encrypt 0123456789012345678901234567890123456789
  # - Paste the output down here
  api_key:
      secure: "ucwdch/H3elGETW4jd4JHlhmE8fulYIY3SGZ9fx1fU/MZs/w4+DmYmUY1GeMt56jE0iidurPnGhITgOUbFImCDVIiJrgHmoBR3RfScQ+ZQ8S0a60Y/x0UfDvqI06hYoZD6B9mnIgOt99QnsY37FxTVNdOOzF8cuUpopA5xr2KUCUyQfM3ZbxmEQInqdedxeN89Y9wuq6zRmYP6Y0vVsDJI0ty8ft3T+Zraqioez6JTRWps8aR2l3pHOQtZ6fF9OKAIaNtsJaxEXu+gJwJ8ikXVwssYV+8DXAzdNkMzFq2cyqmlao9QmxB0qAXAWzFbIZJ1scDB1JYU/etBRav/3lbnPKZCtl2b46MJnwg/w+zYwS3b0OAcS4FlVw9zXsbg4M5vbbw78mGQBSKfRrRm9PFfuB6m7ll5XRjLOpOPE5x8nBoIx0KmjaWoqjcm6hwow06gHFRMi7Qb+kHuupzfl7ko3kWGTbjcD1dU6McKgOOu1fotL5vkctjqiNS4SfaChbADEypcgZZuurV38/v/porJzGKsKsl/Lu4H730rLMXvsQkJkybb1DVhPDTHajLW2KROtSJDBxVrBv6RtZsRgS8N2yjTh33UOWy2/gxFzIdu9CnRjmt0/Zlxo9QP76KHG0c8c+d5aTWqnpRUB4M+azs1GG2UT062uQYM4fKkPCta8="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$BINNAME.*
  on:
    # TODO Here you can pick which targets will generate binary releases
    # In this example, there are some targets that are tested using the stable
    # and nightly channels. This condition makes sure there is only one release
    # for such targets and that's generated using the stable channel
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
