[package]
name = "glrail"
version = "0.1.2"
authors = ["Bjørnar Luteberget <luteberget@gmail.com>"]
edition = "2018"

[dependencies]
imgui-sys-bindgen = { path = "../imgui-sys-bindgen" }
imgui-sys-opengl = { path = "../imgui-sys-opengl" }
sdl2 = "*"
gl = "*"
const-cstr="*"
railplotlib = { path = "../../railplot/lib/railplotlib" }
log="*"
simple-logging="*"
serde_json="*"
smallvec = "0.6"
ordered-float = "*"
