[package]
name = "junc_app"
version = "0.1.0"
authors = ["Bjørnar Luteberget <luteberget@gmail.com>"]
edition = "2018"

[dependencies]
junc_model = { path = "../model" }
junc_calc = { path = "../calc" }
